### ISSUE TITLE
Colima breaks creating new users in local supabase instance

### ISSUE THREAD

**Issue by riccardolardi** [supabase/gotrue#1029]
Minimal demo repository for reproduction:
https://github.com/riccardolardi/test-supabase-colima

Running Colima with this config:

```
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    aarch64    4       6GiB      60GiB    docker
````
And latest `supabase` and `@supabase/supabase-js`

Creation of new users via `supabase.auth.admin.createUser()` or `supabase.auth.signUp()` will result in following error:

```
AuthRetryableFetchError: fetch failed
    at /Users/riccardolardi/Code/test-supabase-colima/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:30:16
    at Generator.next (<anonymous>)
    at /Users/riccardolardi/Code/test-supabase-colima/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/riccardolardi/Code/test-supabase-colima/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:4:12)
    at handleError (/Users/riccardolardi/Code/test-supabase-colima/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:27:40)
    at /Users/riccardolardi/Code/test-supabase-colima/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:87:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  __isAuthError: true,
  status: 0
}
```

Is this related to `gotrue`?

**Comment by kangmingtay** [comment]
hey @riccardolardi, an `AuthRetryableFetchError` means that there is a network issue with connecting to Supabase. Can you please check the network request from your browser and reach out to us at https://app.supabase.com/support/new if you're still facing this issue?
