### ISSUE TITLE
Flow State not found

### ISSUE THREAD

**Issue by Phil9l** [supabase/gotrue#1341]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using self-hosted supabase with gotrue and next js for auth. A few users can't login to the app because they get redirected to the following page every time they try to sign in with google.
```
[GET] /auth/callback?next=%2F&error_description=Flow%20State%20not%20found&error=server_error status=307
```

I haven't found anything unusual about these users.

On the client side I call 

```
            const { error } = await supabase.auth.signInWithOAuth({
              provider: "google",
              options: {
                redirectTo: `${window.location.origin}/auth/callback?next=${window.location.href}`,
                queryParams: {
                  access_type: "offline",
                  prompt: "consent",
                },
              },
            });
```

## To Reproduce

I haven't found why it happens to these specific users. They are using mobile chrome and using the same auth flow as other users. They tried logging in using multiple different google accounts.

1. Go to https://climbest.app/
2. Click on login
3. Be lucky I guess?
4. Get redirected to the `Flow State not found` error.

## Expected behavior

Users can log in to the app.

## Screenshots

https://imgur.com/a/D9WGyMH

## System information

- User agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36`
- OS: Android 10
- Browser: Chrome 120
- Version of supabase-js: 2.39.0
- Version of Node.js: Node.js 18.x

**Comment by hf** [comment]
What libraries do you use with NextJS? Please send us a code snippet that includes the initialization of the Supabase client.

**Comment by Phil9l** [comment]
>  What libraries do you use with NextJS? 

```
    "@supabase/ssr": "^0.0.4",
    "@supabase/supabase-js": "^2.39.0",
```

> Please send us a code snippet that includes the initialization of the Supabase client.

I'm initializing the client like this:
```ts
import { createBrowserClient } from "@supabase/ssr";

const supabase = createBrowserClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);
```

And using like this:
```ts
const { error } = await supabase.auth.signInWithOAuth({
  provider: "google",
  options: {
    redirectTo: `${window.location.origin}/auth/callback?next=${window.location.href}`,
    queryParams: {
      access_type: "offline",
      prompt: "consent",
    },
  },
});
```

I think I copy-pasted code from https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr to my `climbclimb/src/app/auth/callback/route.ts`:
```ts
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { type CookieOptions, createServerClient } from "@supabase/ssr";

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");
  // if "next" is in param, use it as the redirect URL
  const next = searchParams.get("next") ?? "/";

  if (code) {
    const cookieStore = cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          get(name: string) {
            return cookieStore.get(name)?.value;
          },
          set(name: string, value: string, options: CookieOptions) {
            cookieStore.set({ name, value, ...options });
          },
          remove(name: string, options: CookieOptions) {
            cookieStore.delete({ name, ...options });
          },
        },
      }
    );

    try {
      if (!code) {
        throw new Error(
          `code param is missing in ${
            request.url
          }; all params: ${JSON.stringify(searchParams)}`
        );
      }
      const { error } = await supabase.auth.exchangeCodeForSession(code);

      if (!error) {
        return NextResponse.redirect(`${next}`);
      } else {
        console.error(error);
        return NextResponse.redirect(`${origin}/?error=${error.message}`);
      }
    } catch (error: unknown) {
      console.log(error);
      if (error instanceof Error) {
        return NextResponse.redirect(`${origin}/?error=${error.message}`);
      } else {
        return NextResponse.redirect(`${origin}/?error=${error?.toString()}`);
      }
    }
  }

  // return the user to an error page with instructions
  return NextResponse.redirect(`${origin}/auth/auth-code-error`);
}
```

**Comment by nonnster** [comment]
I'm also experiencing the same thing. Some of my google user aren't able to login because of the same problem. @Phil9l were you able to get around this issue?

**Comment by Phil9l** [comment]
> I'm also experiencing the same thing. Some of my google user aren't able to login because of the same problem. @Phil9l were you able to get around this issue?

No, unfortunately, not. More and more users are complaining about it. It's getting pretty critical for us at this point.

**Comment by hf** [comment]
If you are able to reproduce, please send us a HAR recording if possible. You can use https://supabase.help if you want to keep that private, just mention this issue when opening a support ticket.

Some causes of why the error could be happening:

1. Cookie chunking issues -- mobile browsers may be having trouble dealing with larger / multiple cookies.
2. Requesting sign-in from one browser receiving the callback on another. (When using PKCE the sign-in should complete on the same browser it was started on.)
3. The cycle takes too long. Right now this is [300 seconds](https://github.com/supabase/gotrue/blob/master/internal/conf/configuration.go#L673).

As you mentioned self-hosting, please provide us with details of the versions you're using on the server and configuration options related to this.

**Comment by hnykda** [comment]
We have seen that too, but only occasionally and I cannot reproduce that (hence can't share more than just these):

```
TypeError: Cannot read properties of undefined (reading 'call')
    at Object.__webpack_require__ [as require] (/var/task/.next/server/webpack-runtime.js:1:161)
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:111:463
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async rs (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:110:4701)
    at async rT (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:111:27761)
    at async ee (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:24526)
    at async en.responseCache.get.incrementalCache (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:991)
    at async rW.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:448)
    at async rW.renderPageComponent (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:4990)
    at async rW.renderToResponseImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5573)
```

```
[POST] /auth/login?error=server_error&error_description=Flow%20State%20not%20found&next=%2Fquestion-suggestion status=500
```

![image](https://github.com/supabase/gotrue/assets/2741256/937b6dd1-8058-4a14-92b8-766d25bb72b9)

**Comment by JeronimasDargis** [comment]
Hey, I am experiencing the same issue. 
I got this callback URL, unable to replicate it as it was spotted using Pagesense.

`#error=server_error&error_code=422&error_description=Flow+state+not+found`

**Comment by jayhickey** [comment]
We're also seeing this, it's happening 20-40 times a day for our users. Redirect looks like this:

```
/error?error=server_error&error_code=422&error_description=Flow+state+not+found&message=Missing+cod
e#error=server error&error code=422&error_description=Flow+state+not+found
```

**Comment by Forsect** [comment]
Same for us, didn't see any issue like for months, started to happening last week...

**Comment by Jaaneek** [comment]
Same for us, google oauth suddenly doesn't work 30% of the time.

Mostly for mobile users but also happens on Desktop.

**Comment by gvzq** [comment]
We're noticing this same trend in our project using Google Auth. I would greatly appreciate if Supabase can provide us with some guidance.

**Comment by bookerlyio** [comment]
I'm getting this when trying to confirm emails using a callback url

const { error } = await supabase.auth.exchangeCodeForSession(code);

**Comment by xeladotbe** [comment]
I have the same problem, as auth-code a uuid v4 is expected, but from the provider I only get back a code (i.e. ANbOebvxVXCktJlSDXTU) which is not found in the DB (obviously), I don't know where the uuid v4 should come from that is searched for in https://github.com/supabase/auth/blob/master/internal/api/token.go#L258

**Comment by J0** [comment]
Hey @Jaaneek 

Thanks for the report - do you recall if there's a specific reproducible scenario where this happens? We'd like to dig in further.
> Same for us, google oauth suddenly doesn't work 30% of the time.
> Mostly for mobile users but also happens on Desktop.

**Comment by kor-bim** [comment]
help same issue

**Comment by msssrp** [comment]
> ~help same issue, kakao provider too~ --- i handle it
> 
> In my case, the error occurred because Nginx received a header from Google that was too large to process

You just saved my life thank you.

**Comment by J0** [comment]
Thanks @hotay this is useful

**Comment by kirkstrobeck** [comment]
After `supabase.auth.exchangeCodeForSession` I returned a page that performed a redirect, when I just return `return NextResponse.redirect(requestUrl.origin);` the problem goes away. I suspect its a race condition with setting/reading the cookie

**Comment by chris-feist** [comment]
What I realized was happening in my case is that during sign up, resource creation was taking longer than 5 seconds, so the oauth callback was retried. The retried request always failed with this error since I assume the code was already read/processed. I'm using Remix, so I ended up running async functions in parallel to speed up my loader and using [Streaming](https://remix.run/docs/en/main/guides/streaming) for a better UX.

**Comment by hoiheart** [comment]
It's the same situation with docker self host method.

```yml
# docker-compose.yml

# Add google environment
GOTRUE_EXTERNAL_GOOGLE_ENABLED: ${ENABLE_GOOGLE_SIGNUP}
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
GOTRUE_EXTERNAL_GOOGLE_SECRET: ${GOOGLE_SECRET}
GOTRUE_EXTERNAL_GOOGLE_SKIP_NONCE_CHECK: ${GOOGLE_SKIP_NONCE_CHECK}
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: "http://localhost:3000/auth/callback"
```

```ts
// actions.ts

export const signInAction = async () => {
  const supabase = await createClient();

  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: 'http://localhost:3000/auth/callback',
    },
  });

  if (error) {
    return encodedRedirect('error', '/sign-in', error.message);
  }

  // data.url returns localhost:8000/auth/v1/authorize.
  return redirect(data.url);
};
```

```ts
// /auth/callback/route.ts

import { NextResponse } from 'next/server'
import { createClient } from '@/utils/supabase/server'

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url)
  const code = searchParams.get('code')
  const next = searchParams.get('next') ?? '/'

  /* searchParams
    {
        'state' => 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkxODc3NDAsInNpdGVfdXJsIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJmdW5jdGlvbl9ob29rcyI6bnVsbCwicHJvdmlkZXIiOiJnb29nbGUiLCJyZWZlcnJlciI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC8iLCJmbG93X3N0YXRlX2lkIjoiYjZhODgwNTEtODMwNi00ZGNhLWJiNGItMGRjMzFjYzYzOGEwIn0.###...',
        'code' => '4/0ASVgi3KfTw06s-SAHY32Ps_t9R-###...',
        'scope' => 'email profile openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email',
        'authuser' => '0',
        'prompt' => 'consent'
    }
   */

  if (code) {
    const supabase = await createClient()
    const { error } = await supabase.auth.exchangeCodeForSession(code)
    /**
        Error occurred between authentication
        [Error [AuthApiError]: invalid flow state, no valid flow state found] {
           __isAuthError: true,
           status: 404,
           code: 'flow_state_not_found'
        }
    */
    if (!error) {
      const forwardedHost = request.headers.get('x-forwarded-host')
      const isLocalEnv = process.env.NODE_ENV === 'development'
      if (isLocalEnv) {
        return NextResponse.redirect(`${origin}${next}`)
      } else if (forwardedHost) {
        return NextResponse.redirect(`https://${forwardedHost}${next}`)
      } else {
        return NextResponse.redirect(`${origin}${next}`)
      }
    }
  }

  return NextResponse.redirect(`${origin}/auth/auth-code-error`)
}
```

Where should I set redirect_uri between application domain localhost:3000 and API domain localhost:8000 in env and google oauth settings?
I've tried many directions, but all of them have slightly different errors and I couldn't succeed.

**Comment by proxybase-user** [comment]
I'm having the same issue on google on self hosted...Any way to fix this ?

**Comment by johndpope** [comment]
im self hosting - when i check docker container 
(ive gone through google sign in many times )

<img width="875" alt="Image" src="https://github.com/user-attachments/assets/b6b06504-c1e8-4b5a-ad33-cf57854d7084" />

**docker-compose logs auth**
i see the inserts 
i see the error - 

https://mywebsite.com/auth/v1/token?grant_type=pkce

grant_type: pkce
{auth_code: "4/0Ab_5qlmQXkW5fewhd38uT4GJu01KQM2-Uza3bnPKB1ucvLrliEpLjDqrZLyhT-oigaQprg",…}
auth_code
: 
"4/0Ab_5qlmQXkW5fewhd38uT4GJu01KQM2-Uza3bnPKB1ucvLrliEpLjDqrZLyhT-oigaQprg"
code_verifier
: 
"c92db6530ed056b3754ac4598af499cdeda88ffd9ce1e11f9a3b1ea21504816b438ae7a5a0c315e1b5668882d32efd07d48a01f637d2dc87"





```shell
2025/04/30 12:53:45 stderr: [POP] 2025/04/30 12:53:45 sql - INSERT INTO "flow_state" ("auth_code", "auth_code_issued_at", "authentication_method", "code_challenge", "code_challenge_method", "created_at", "id", "provider_access_token", "provider_refresh_token", "provider_type", "updated_at", "user_id") VALUES (:auth_code, :auth_code_issued_at, :authentication_method, :code_challenge, :code_challenge_method, :created_at, :id, :provider_access_token, :provider_refresh_token, :provider_type, :updated_at, :user_id) | [&{c745d9f4-8f41-4c89-aa11-8daff5632e43 <nil> bc2b4a0e-afdd-4333-afc4-704a3c318ab7 oauth Cs5LHDZeP9F0nYQnhiuGGGfGc3v8I1QHJFR2JJkYaCs s256 google   <nil> 2025-04-30 12:53:45.350436 +0000 UTC 2025-04-30 12:53:45.350436 +0000 UTC}] (conn=conn-4760421034211792560, tx=0, maxconn: 0, openconn: 1, in-use: 0, idle: 1)
2025/04/30 12:53:45 stderr: {"component":"api","duration":362696066,"level":"info","method":"GET","msg":"request completed","path":"/authorize","referer":"https://blabla.com/auth/callback","remote_addr":"10.0.1.200","request_id":"b7f5ed71-64d0-4b7f-b81c-178366cc9c0f","status":302,"time":"2025-04-30T12:53:45Z"}
2025/04/30 12:54:00 stderr: {"level":"info","msg":"Request received external host in X-Forwarded-Host or Host headers, but the values have not been added to GOTRUE_MAILER_EXTERNAL_HOSTS and will not be used. To suppress this message add the host, or sanitize the headers before the request reaches Auth.","time":"2025-04-30T12:54:00Z","x_forwarded_host":"\\supabase.nonprod.aws.mailopoly.com","x_forwarded_proto":"http"}
2025/04/30 12:54:00 stderr: [POP] 2025/04/30 12:54:00 sql - SELECT flow_state.auth_code, flow_state.auth_code_issued_at, flow_state.authentication_method, flow_state.code_challenge, flow_state.code_challenge_method, flow_state.created_at, flow_state.id, flow_state.provider_access_token, flow_state.provider_refresh_token, flow_state.provider_type, flow_state.updated_at, flow_state.user_id FROM flow_state AS flow_state WHERE auth_code = $1 LIMIT 1 | ["4/0Ab_5qlmQXkW5fewhd38uT4GJu01KQM2-Uza3bnPKB1ucvLrliEpLjDqrZLyhT-oigaQprg"] (conn=conn-4760421034211792560-UeTesp, tx=0)
2025/04/30 12:54:00 stderr: {"component":"api","error":"404: invalid flow state, no valid flow state found","level":"info","method":"POST","msg":"404: invalid flow state, no valid flow state found","path":"/token","referer":"https://blabla.com/","remote_addr":"10.0.1.200","request_id":"db9c4676-6eab-46b4-a1fd-face8ed02f98","time":"2025-04-30T12:54:00Z"}
2025/04/30 12:54:00 stderr: {"component":"api","duration":11531054,"error_code":"flow_state_not_found","level":"info","method":"POST","msg":"request completed","path":"/token","referer":"https://blabla.com/","remote_addr":"10.0.1.200","request_id":"db9c4676-6eab-46b4-a1fd-face8ed02f98","status":404,"time":"2025-04-30T12:54:00Z"}
2025/04/30 12:54:00 stderr: {"level":"info","msg":"Request received external host in X-Forwarded-Host or Host headers, but the values have not been added to GOTRUE_MAILER_EXTERNAL_HOSTS and will not be used. To suppress this message add the host, or sanitize the headers before the request reaches Auth.","time":"2025-04-30T12:54:00Z","x_forwarded_host":"\\supabase.nonprod.aws.mailopoly.com","x_forwarded_proto":"http"}
2025/04/30 12:54:00 stderr: [POP] 2025/04/30 12:54:00 sql - SELECT flow_state.auth_code, flow_state.auth_code_issued_at, flow_state.authentication_method, flow_state.code_challenge, flow_state.code_challenge_method, flow_state.created_at, flow_state.id, flow_state.provider_access_token, flow_state.provider_refresh_token, flow_state.provider_type, flow_state.updated_at, flow_state.user_id FROM flow_state AS flow_state WHERE auth_code = $1 LIMIT 1 | ["4/0Ab_5qlmQXkW5fewhd38uT4GJu01KQM2-Uza3bnPKB1ucvLrliEpLjDqrZLyhT-oigaQprg"] (conn=conn-4760421034211792560-hFOMCk, tx=0)
2025/04/30 12:54:00 stderr: {"component":"api","error":"404: invalid flow state, no valid flow state found","level":"info","method":"POST","msg":"404: invalid flow state, no valid flow state found","path":"/token","referer":"https://blabla.com/","remote_addr":"10.0.1.200","request_id":"84ed4342-b99b-4409-94f5-6d248ab1ea79","time":"2025-04-30T12:54:00Z"}
2025/04/30 12:54:00 stderr: {"component":"api","duration":5640007,"error_code":"flow_state_not_found","level":"info","method":"POST","msg":"request completed","path":"/token","referer":"https://blabla.com/","remote_addr":"10.0.1.200","request_id":"84ed4342-b99b-4409-94f5-6d248ab1ea79","status":404,"time":"2025-04-30T12:54:00Z"}
```

UPDATE
re-reading @chris-feist  - maybe this is root cause. timeout issue or cookie size on nginx. 
i do an audit by truncated the authflow table.

**Comment by josuebrunel** [comment]
I'm also having the same with Google (self hosted)

**Comment by johndpope** [comment]
temp fix - 


SELECT flow_state.auth_code, flow_state.auth_code_issued_at, flow_state.authentication_method, flow_state.code_challenge, flow_state.code_challenge_method, flow_state.created_at, flow_state.id, flow_state.provider_access_token, flow_state.provider_refresh_token, flow_state.provider_type, flow_state.updated_at, flow_state.user_id FROM flow_state AS flow_state;




DELETE FROM auth.refresh_tokens WHERE updated_at < NOW() - INTERVAL '1 day' OR revoked = true;

**Comment by josuebrunel** [comment]
Thanks. For me it seems to be a configuration issue. Just figured it out. 
I have a self hosted *supabase-auth* (auth:8193) and  a *Go app* (app:8190). My issue came from the fact that the *GOOGLE_EXTERNAL_X_REDIRECT* value was my *app callback* instead of *supabase-auth callback*
```
GOTRUE_EXTERNAL_GOOGLE_ENABLED=true
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=<clientid>
GOTRUE_EXTERNAL_GOOGLE_SECRET=<secret>
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=http://auth:8193/callback # Good. redirect for supabase-auth
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=http://app:8190/callback # Bad redirect for my app
```
1. In the *env*, the *redirect_uri* is the one for *supbase-base* 
2. In your app, when calling `http://auth/authorize`, the *redirect_to* to pass is the one from your application (in my case *http://app:8090/callback*). Supabase-auth will return an url and a verifier, store the later ( encrypepted cookie or whatever)
3. Once supabase-auth is done with the OAuth2 flow, it will request the *redirect_to* with a *code (auth_code)*
4. In your callback/redirect_to handler/controller pass the *code* + *verifier* + *grant_type* to the supbase-auth via */token*

Voila!

**Comment by johndpope** [comment]
yes - i have GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI working with a hosted react site with an external self hosted supabaes ssl site - and basically the app hands off sign in to google - and then google successfully hits the external supabase endpoint - and then website comes good with the callback. it took a few days and eyeballs to work this out.

**Comment by tronghieu60s** [comment]
Thank @johndpope. Below is the full configuration to use google login on supabase self hosted.

Create a file `docker-compose.override.yml` like this:

```
services:
  auth:
    ports:
      - 9999:9999/tcp
    environment:
     GOTRUE_EXTERNAL_GOOGLE_ENABLED: ${ENABLE_GOOGLE_SIGNUP}
     GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
     GOTRUE_EXTERNAL_GOOGLE_SECRET: ${GOOGLE_CLIENT_SECRET}
     GOTRUE_EXTERNAL_GOOGLE_SKIP_NONCE_CHECK: false
     GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
```

And add this to .env files:

```
# Google Authentication
ENABLE_GOOGLE_SIGNUP=true
GOOGLE_CLIENT_ID=309062107014-aosusl84n0tror61lbv88jhtph91smt3.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_REDIRECT_URI=https://url-auth/callback
```

The domain "https://url-auth/" maps to port 9999 (supabase-auth)

**Comment by philipb42web** [comment]
Been hitting the "flow_state_not_found" error for a couple days (capacitor/next.js).

It was a client side data corruption of the PKCE verifier (stored keys over-processing), basically the storage adapter (Preferences) was JSON.parse()-ing the values it retrieved. 

The problem was that Supabase auth-js library expected the raw string for the auth token verifier,..so when it parsed it - the verifier was thrown back to Supabase in wrong format during the 'exchangeCodeForSession' call (this led to the backend rejecting the flow state).

What helped is alleviating the parsing logic -  making the storage adapter bring back the value from capacitor preferences directly;





`async getItem(key) {`
      `const { value } = await Preferences.get({ key });`
      `return` JSON.parse(value); // <----------- That was the issue
  }



 `async getItem(key) {`
      `const { value } = await Preferences.get({ key });`
      `return value; **// <----------- grabs the data from phone's storage and shoves it straight to Supabase**
  }`
