### ISSUE TITLE
AuthApiError: Error sending confirmation mail

### ISSUE THREAD

**Issue by psiaux** [supabase/gotrue#1388]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Sometimes, the sign up function returns the following error:
`AuthApiError: Error sending confirmation mail
      at handleError (webpack-internal:///(action-browser)/./node_modules/.pnpm/@supabase+gotrue-js@2.62.0/node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:46:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _handleRequest (webpack-internal:///(action-browser)/./node_modules/.pnpm/@supabase+gotrue-js@2.62.0/node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:93:9)
      at async _request (webpack-internal:///(action-browser)/./node_modules/.pnpm/@supabase+gotrue-js@2.62.0/node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:73:18)
      at async SupabaseAuthClient.signUp (webpack-internal:///(action-browser)/./node_modules/.pnpm/@supabase+gotrue-js@2.62.0/node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:236:23)
      at async signUp (webpack-internal:///(action-browser)/./src/app/cadastro/_actions/index.ts:26:17)
      at async project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:406
      at async t4 (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:6379)
      at async rk (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:25934)
      at async doRender (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1394:30)
      at async cacheEntry.responseCache.get.routeKind (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1555:28)
      at async DevServer.renderToResponseWithComponentsImpl (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1463:28)
      at async DevServer.renderPageComponent (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1856:24)
      at async DevServer.renderToResponseImpl (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1894:32)
      at async DevServer.pipeImpl (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:911:25)
      at async NextNodeServer.handleCatchallRenderRequest (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:271:17)
      at async DevServer.handleRequestImpl (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:807:17)
      at async project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:331:20
      at async Span.traceAsyncFn (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\trace\trace.js:151:20)
      at async DevServer.handleRequest (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:328:24)
      at async invokeRender (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:163:21)
      at async handleRequest (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:342:24)
      at async requestHandlerImpl (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:366:13)
      at async Server.requestListener (project_folder\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\start-server.js:140:13) {
    __isAuthError: true,
    status: 500
  }`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

`const res = await supabase.auth.signUp({ email, password })`
 
`if (res.error !== null) console.log({ signup_error: res.error })`

## Expected behavior

`res.error` should be `null`.

## System information

- OS: Windows 10
- Browser Brave
- Version of @supabase/ssr: ^0.0.10
- Version of Node.js: v20.9.0

## Additional context

I'm using Next.js and Supabase's integration with Resend (as custom SMTP). The trace log above is from local development. The production log is somewhat different and doesn't give as much information:
```
p [AuthApiError]: Error sending magic link
      at n (/var/task/.next/server/chunks/911.js:1:45608)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async m (/var/task/.next/server/chunks/911.js:1:46578)
      at async o (/var/task/.next/server/chunks/911.js:1:46233)
      at async r.signInWithOtp (/var/task/.next/server/chunks/911.js:1:15916)
      at async i (/var/task/.next/server/app/login/page.js:1:10462)
      at async /var/task/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:406
      at async rg (/var/task/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6309)
      at async rz (/var/task/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24709)
      at async Y (/var/task/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25417) {
    __isAuthError: true,
    status: 500
  }
```

**Comment by kangmingtay** [comment]
hi @psiaux, can you please reach out to us via support at http://supabase.help? this is usually an indication that your custom SMTP server config is incorrect

**Comment by mousindev** [comment]
Hi all, I am receiving the same error all of a sudden (was working fine few days ago and don't recall having made any change in this area) and in my case I am not using ReSend or any other service, it is Supabase sending the email. 
The funny thing is that despite the error received when using the function `signInWithOtp()` the email arrives correctly, but then when I try to verify the OTP code with `verifyOtp()` I get a second error that looks like this:

```
AuthApiError: Token has expired or is invalid
    at handleError (webpack-internal:///(action-browser)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:46:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (webpack-internal:///(action-browser)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:93:9)
    at async _request (webpack-internal:///(action-browser)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:73:18)
    at async SupabaseAuthClient.verifyOtp (webpack-internal:///(action-browser)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:615:37)
    at async verifyEmailWithOTP (webpack-internal:///(action-browser)/./app/_services/auth.ts:100:29)
    at async /node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:406
    at async t0 (/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:5773)
    at async rh (/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:23636)
    at async doRender (/node_modules/next/dist/server/base-server.js:1391:30)
    at async cacheEntry.responseCache.get.routeKind (/node_modules/next/dist/server/base-server.js:1552:28)
    at async DevServer.renderToResponseWithComponentsImpl (/node_modules/next/dist/server/base-server.js:1460:28)
    at async DevServer.renderPageComponent (/node_modules/next/dist/server/base-server.js:1843:24)
    at async DevServer.renderToResponseImpl (/node_modules/next/dist/server/base-server.js:1881:32)
    at async DevServer.pipeImpl (/node_modules/next/dist/server/base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (/node_modules/next/dist/server/next-server.js:266:17)
    at async DevServer.handleRequestImpl (/node_modules/next/dist/server/base-server.js:805:17) {
  __isAuthError: true,
  status: 401
```

**Comment by mousindev** [comment]
Hi, in my case I found what is creating the issue. I added yesterday two triggers on `auth.users` listening to the creation and the update of an user, that will call a function to either replicate or update the user  into the table `public.users`. 
I guess the `supabaseauth.signInWithOTP()` method updates the user (maybe the last time it was sent a magic link / OTP?) and by getting the 500 I am guessing there is an error in my update function (though is the same I used in another project with the exact same schema, but will look closer into it)

**Comment by re-masashi** [comment]
Any updates ? I have been stuck on this error for days.

**Comment by kangmingtay** [comment]
@mousindev did you check if it works properly when the triggers are removed?

@re-masashi we need you to elaborate on the steps in order for us to investigate further - please reach out to us at https://supabase.help

**Comment by mousindev** [comment]
Hi all. Yes, there was an issue in the functions that were triggered, and that was causing the error.

**Comment by kangmingtay** [comment]
@re-masashi that means that you've set up the custom SMTP service for gmail wrongly - have you seen [this discussion](https://github.com/orgs/supabase/discussions/5320#discussioncomment-7836793) yet where i've outlined how to set this up properly?

**Comment by re-masashi** [comment]
i checked some parts. It was working previously, so I doubt if it was a 2FA problem with Gmail. I'll still post updates after making some changes based on that discussion. thanks for the pointer

**Comment by re-masashi** [comment]
> @re-masashi that means that you've set up the custom SMTP service for gmail wrongly - have you seen [this discussion](https://github.com/orgs/supabase/discussions/5320#discussioncomment-7836793) yet where i've outlined how to set this up properly?

I don't think Gmail is a problem, since I'm using Brevo's SMTP on port 587. But I'm not sure

**Comment by re-masashi** [comment]
> @re-masashi that means that you've set up the custom SMTP service for gmail wrongly - have you seen [this discussion](https://github.com/orgs/supabase/discussions/5320#discussioncomment-7836793) yet where i've outlined how to set this up properly?

I don't think Gmail is a problem, since I'm using Brevo's SMTP on port 587. But I'm not sure
