### ISSUE TITLE
Selfhosted: Supabase-Auth Go Problem with invalid memory address or nil pinter dereference

### ISSUE THREAD

**Issue by MerlinChiodo** [supabase/gotrue#791]
# Bug report

## Describe the bug

 Supabase container keeps on restarting. (loops)
```supabase-auth | {"level":"info","msg":"Go runtime metrics collection started","time":"2022-11-03T10:19:40Z"}
supabase-auth | {"level":"info","msg":"received graceful shutdown signal","time":"2022-11-03T10:19:40Z"}
supabase-auth | panic: runtime error: invalid memory address or nil pointer dereference
supabase-auth | [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x6073b4]
supabase-auth |
supabase-auth | goroutine 1 [running]:
supabase-auth | net/url.(*URL).Query(0xc000046017?)
supabase-auth |         /usr/local/go/src/net/url/url.go:1104 +0x14
supabase-auth | github.com/netlify/gotrue/cmd.migrate(0xc0005bfcf8?, {0xc0005bfcd0?, 0x0?, 0x0?})
supabase-auth |         /go/src/github.com/netlify/gotrue/cmd/migrate_cmd.go:55 +0x216
supabase-auth | github.com/netlify/gotrue/cmd.glob..func4(0x1849480, {0x189ae00?, 0x0?, 0x0?})
supabase-auth |         /go/src/github.com/netlify/gotrue/cmd/root_cmd.go:17 +0x25
supabase-auth | github.com/spf13/cobra.(*Command).execute(0x1849480, {0xc00010c1d0, 0x0, 0x0})
supabase-auth |         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
supabase-auth | github.com/spf13/cobra.(*Command).ExecuteC(0x1849480)
supabase-auth |         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
supabase-auth | github.com/spf13/cobra.(*Command).Execute(...)
supabase-auth |         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
supabase-auth | github.com/spf13/cobra.(*Command).ExecuteContext(...)
supabase-auth |         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
supabase-auth | main.main()
supabase-auth |         /go/src/github.com/netlify/gotrue/main.go:31 +0x139```

## To Reproduce

1. Starting the docker-compose with: docker-compose -f docker-compose.yml up
2. and this Bugs shows again and again in console

## System information

- OS: Ubuntu Server 2204 (VM Machine on Windows 11 in VM Workstation 16 Pro)
- Version of supabase-js: latest docker supabase version

## Additional context

Is it a version problem with GO? Found something abount a version problem with a a bit different bug in the web.

Thank you :)

**Comment by MerlinChiodo** [comment]
![image](https://user-images.githubusercontent.com/60719496/199699080-0e2541ca-e1b4-46ad-88ad-5f7df58f16fc.png)

**Comment by MerlinChiodo** [comment]
Anyone having this bug, cloning project new and start with initial (clone example.env) works for me. So probably it was caused due to a Password in env with special chars or there was a fix in a new image release
